-- Crea la nueva migración para la tabla `APPOINTMENTS`
ALTER TABLE `APPOINTMENTS`
ADD CONSTRAINT `UNIQUE_OFFICE_TIME` UNIQUE (`OFFICE_ID`, `APPOINTMENT_TIME`),
ADD CONSTRAINT `UNIQUE_DOCTOR_TIME` UNIQUE (`DOCTOR_ID`, `APPOINTMENT_TIME`),
ADD CONSTRAINT `UNIQUE_PATIENT_TIME` UNIQUE (`PATIENT_NAME`, `APPOINTMENT_TIME`);

-- Crear un índice para verificar las citas por doctor en un día
CREATE INDEX `IDX_DOCTOR_DATE` ON `APPOINTMENTS` (`DOCTOR_ID`, `APPOINTMENT_TIME`);
